### ISSUE TITLE
[Benchmarking - Event] - Add breadcrumbs to current event

### ISSUE THREAD

**Issue by JessicaFM** [inab/openEBench-nuxt-v3#38]
In Benchmarking - Event view we need to add the breadcrumbs form to "selected event" (current event):
![ex1](https://github.com/user-attachments/assets/9bceed09-7dc5-4d13-85cf-d5a3b5763d04)

Needed to add "Events List" and "Current Event"

Home/Benchmarking Communities/_**QfO Events**_/**_Quest for Orthologs - 2022 Reference Proteomes_**

_**QfO Events**_: this is  "Events List"
**_Quest for Orthologs - 2022 Reference Proteomes_**: this is "Current Event"

"Events links" need to be linked to "Events page" (.../benchmarking/OEBC002/events)

**Comment by AniValle** [comment]
Make redirect to current event.
