### ISSUE TITLE
[NAVBAR & PAGES HEADERS COLAPSEDS] - Homogenializar the chevron directions

### ISSUE THREAD

**Issue by JessicaFM** [inab/openEBench-nuxt-v3#68]
![navbar2](https://github.com/user-attachments/assets/60246ac4-84ab-4e56-985d-756edc243006)

Its ok make nabvar chevron directions to right directions, but all chevron has to have the same design.

**Comment by AniValle** [comment]
Tienen el mismo diseño solo que en la barra de navegación están cerrados por defecto o sea que los chevron están hacia la derecha, y en Benchmarking el acordeón está por defecto abierto o sea que el chevron esta hacia abajo.
La lógica de los chevron es que si está cerrado se dirigen a la derecha y si está abierto hacia abajo, así está en todo.

**Comment by Androidbeingx** [comment]
Creo que en si todos tienen la miasma logica menos los de los widgets?
Quiza se refiere tambien al color ?

**Comment by JessicaFM** [comment]
Si ya tienen todos los menus / submenus, y containers dentro de pàginas, la misma dirección en abierto / cerrado (no collapse / collapse), ya podemos cerrar la issue
